version: 2

updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'cron'
      cronjob: '0 3 * * *'
      timezone: 'Europe/Rome'
    cooldown:
      default-days: 1
    commit-message:
      prefix: 'chore'
      prefix-development: 'chore'
      include: 'scope'

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'cron'
      cronjob: '0 3 * * *'
      timezone: 'Europe/Rome'
    cooldown:
      default-days: 1
    commit-message:
      prefix: 'chore'
      include: 'scope'
